CREATE TABLE book(
book_id BIGINT NOT NULL AUTO_INCREMENT,
status VARCHAR(10) NOT NULL,
name VARCHAR(255) NOT NULL,
author VARCHAR(255) NOT NULL,
description VARCHAR (1000),
purchased_date DATETIME NOT NULL,
category_id LONG NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
PRIMARY KEY (book_id)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;